### ISSUE TITLE
[Feature Request] Add support for enabling and disabling "Away Mode"

### ISSUE THREAD

**Issue by d-walsh** [mezz64/pyEight#33]
It would be great to be able to enable and disable "Away Mode" through pyEight.

**Comment by maddox** [comment]
🙏

**Comment by mezz64** [comment]
I'm looking into this. Eight has increased the minimum android version on the app so my old dev setup to proxy and sniff the traffic doesn't work anymore. Once I work past that this is easy to add as long as it goes through the rest API.

**Comment by mezz64** [comment]
Finally get setup with an alternative dev setup so I could look at the traffic.  Unfortunately, the api call for away mode is passed through a different end-point that uses OAuth authentication.  They appear to use a hardcoded client-id and secret to allow generation of the bearer token and that information is not something I would want to publish without their authorization.  Especially since it's possible the app is generating those values locally based on device/user identifiers, making the values I see unique to me.

I'm afraid there isn't really a suitable path to add this functionality at this time.
